remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Padlock Documentation
description: Documentation for the Padlock post-quantum encoding utility
show_downloads: true
github:
  is_project_page: true
  repository_url: https://github.com/blues/padlock